---
title: "RESI CI construction -- Simple case"
author: "Kaidi Kang"
output: 
  html_document:
    toc: true
    number_sections: true
    use_bookdown: yes
    code_folding: hide
    toc_float: 
      collapsed: false

link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(magrittr)
library(qwraps2)
library(latticeExtra)
library(parallel)
source("../R/nccd.r")
source("../R/ncf.r")
source("../R/boot.ci.r")
```

# Simulations 1 - evaluating the coverages of each 

```{r, eval = FALSE}
SimFunc <- function(n = 100, alpha = 0.05, m = 1, S = 0.6){
  beta = sqrt(S^2) # true beta
  # simulate x and y
  x = rnorm(n*m) %>% matrix(ncol = m)
  y = x %*% beta + rnorm(n)
  model <- lm(y~ -1 + x)
  beta.hat <- coef(model)
  
  xTx = sum(x^2)
  
  # 1. when sigma is known (sigma = 1)
  # S.hat.norm <- sqrt(beta.hat^2 / (1/sum(x^2)))
  S.hat.norm <- sqrt(beta.hat^2)
  bias.norm <- S.hat.norm - S
  
  # beta.CI = beta.hat + c(-1, 1) * qnorm(1-alpha/2) * sqrt(1/sum(x^2))  
  # Constructing the CI for beta from non-central dist
  z = beta.hat/sqrt(1/sum(x^2)) # normal dist
  chi = z^2 # Chi-sq (1)
  CI_ncp = ncc.ints(yl = sqrt(chi), p = 1, alpha = alpha)[1, ]^2 # this function produces CI for \sqrt(chi^2)
  # CI for beta^2
  # beta2.CI = CI_ncp* (1/sum(x^2))
  # beta.CI = sqrt(beta2.CI)
  # CI for S
  S.CI.norm = sqrt(CI_ncp/n)
  
  # whether the CI for beta covers the true S
  # beta.cvg.norm = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.norm <- c(0, sqrt(max(abs(beta.CI))^2))
  # } else {
  #   S.CI.norm <- c(sqrt(min(abs(beta.CI))^2), sqrt(max(abs(beta.CI))^2))
  # }

  
  # when sigma in unknwon
  # 2. naive estimator for sigma^2
  resd <- residuals(model)
  sigma2_y.hat <- sum(resd^2)/(n-m)
  sigma2_x.hat <- xTx/n
  var.beta.hat = (xTx/n)^(-1) * sigma2_y.hat / n
  
  S.hat.t <- sqrt(beta.hat^2/ (n*var.beta.hat))
  bias.t = S.hat.t - S
  
  t = beta.hat/sqrt(var.beta.hat) # t dist w. df = 1
  f = t^2 # F(1, n-1)
  CI_ncp = ncf.ci(y = f, df1 =1, df2 = n-1, alpha = alpha) 
  S.CI.t = sqrt(CI_ncp/n)
  
  # beta.CI = beta.hat + c(-1, 1) * c( qt(1-alpha/2, df = n-1) * sqrt(var.beta.hat) )
  
  # whether the CI for beta covers the true S
  # beta.cvg.t = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.t <- c(0, sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat ) ) )
  # } else {
  #   S.CI.t<- c(sqrt(min(abs(beta.CI))^2 /(n*var.beta.hat) ), sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat) ))
  # }
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.t <- c(0, sqrt(max(abs(beta.CI))^2  ) )
  # } else {
  #   S.CI.t<- c(sqrt(min(abs(beta.CI))^2  ), sqrt(max(abs(beta.CI))^2  ))
  # }
  
  # 3. using HC3 estimator
  var.beta.hat <- sandwich::vcovHC(model)
  
  beta.CI = beta.hat + c(-1, 1) * c( qt(1-alpha/2, df = n-1)*sqrt(var.beta.hat) )
  
  # whether the CI for beta covers the true S
  # beta.cvg.robust = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  
  S.hat.robust <- sqrt(beta.hat^2/ (n*var.beta.hat))
  bias.robust <- S.hat.robust - S
  
  # Constructing CI for S using non-central F and transformation
  t = beta.hat/sqrt(var.beta.hat) # t dist w. df = 1
  f = t^2 # F(1, n-1)
  CI_ncp = ncf.ci(y = f, df1 =1, df2 = n-1, alpha = alpha) 
  S.CI.robust = sqrt(CI_ncp/n)
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.robust<- c(0, sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat )) )
  # } else {
  #   S.CI.robust<- c(sqrt(min(abs(beta.CI))^2 /(n*var.beta.hat) ), sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat) ))
  # }
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.robust<- c(0, sqrt(max(abs(beta.CI))^2 ) )
  # } else {
  #   S.CI.robust<- c(sqrt(min(abs(beta.CI))^2  ), sqrt(max(abs(beta.CI))^2))
  # }
  
  output = c(
            # normal
             S.hat.norm, bias.norm, 
             S.CI.norm,
             coverage.norm = (S >= S.CI.norm[1] & S <= S.CI.norm[2]), 
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.norm.prob = S < S.CI.norm[1],
             UL.norm.prob = S > S.CI.norm[2],
             # beta.cvg.norm, 
             # t-dist
             S.hat.t, bias.t,
             S.CI.t,
             coverage.t = (S >= S.CI.t[1] & S <= S.CI.t[2]),
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.t.prob = S < S.CI.t[1],
             UL.t.prob = S > S.CI.t[2],
             # beta.cvg.t, 
             # robust
             S.hat.robust, bias.robust,
             S.CI.robust,
             coverage.robust = (S >= S.CI.robust[1] & S <= S.CI.robust[2]),
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.prob.robust = S < S.CI.robust[1],
             UL.prob.robust = S > S.CI.robust[2]
             # beta.cvg.robust
             )
  
  name_list1 = c("S.hat.", "Bias.", "LL.", "UL.", "coverage.", "LL.prob.", "UL.prob.")
  name_list2 = c("norm", "t", "robust")
  names(output) = c(paste0(rep(name_list1, times = length(name_list2)), 
                           rep(name_list2, each = length(name_list1))) )
  return(output)
} # end of SimFunc()
```

```{r sim_setting, eval=FALSE}
set.seed(1213)
nsim = 1000
alpha = 0.05
ns = c(50, 100, 150, 250, 500)
Ss = seq(0, 0.9, by = 0.1)

name_list1 = c("S.hat.", "Bias.", "LL.", "UL.", "coverage.", "LL.prob.", "UL.prob.")
name_list2 = c("norm", "t", "robust")

out = expand.grid(n = ns, S = Ss)
names <- SimFunc(n = 10, S = 0.1) %>% names()

for (n in ns){
  for (S in Ss){
    message(paste(n, S), collapse = ",")
    temp = replicate(nsim, SimFunc(n = n, S = S)) %>% t()
    out[which(out$n == n & out$S == S), names] <- c(var(temp[, 1]), colMeans(temp[, 2:7] ) ,
                                                    var(temp[, 8]), colMeans(temp[, 9:14]),
                                                    var(temp[, 15]), colMeans(temp[, 16:21])
                                                    )
  }
}

# write.csv(out, "Simulation outputs/CIs_Simple_Case_Apr13.csv")
```

# Plots
```{r}
out = read.csv("Simulation outputs/CIs_Simple_Case_Apr13.csv", header = TRUE)
out$S_lab = paste("S =", out$S) # convert to label string
```

```{r}
trellis.device(color=FALSE, new=FALSE)

test = xyplot(coverage.norm + coverage.t + coverage.robust ~ n | S_lab , 
              data=out, 
              type='b', lwd=2,
              ylab='Coverage', xlab = 'Sample size',
              panel= function(x, y, ...){
                panel.grid()
                panel.xyplot(x, y, ..., col='black')
                panel.abline(h=0.95, col='gray', ..., lty=2)
                }, 
              main='CI coverage',
              key = list(columns = 3,
                         text = list(lab = c("normal", "t", "robust")),
                         points = list(pch =c(1, 3, 6)))
              )
print(test)
```

```{r, eval=FALSE}
## Using CI for beta to cover S
trellis.device(color=FALSE, new=FALSE)

test = xyplot(beta.CI.cvg.norm + beta.CI.cvg.t + beta.CI.cvg.robust ~ n | S_lab , 
              data=out, 
              type='b', lwd=2,
              ylab='Coverage', xlab = 'Sample size',
              ylim = c(0.9, 1),
              panel= function(x, y, ...){
                panel.grid()
                panel.xyplot(x, y, ..., col='black')
                panel.abline(h=0.95, col='gray', ..., lty=2)
                }, 
              main='Using CI for beta to cover S',
              key = list(columns = 3,
                         text = list(lab = c("normal", "t", "robust")),
                         points = list(pch =c(1, 3, 6)))
              )
print(test)
```



```{r}
trellis.device(color=FALSE, new=FALSE)

test = xyplot(Bias.norm + Bias.t + Bias.robust ~ n |S_lab, 
              data=out, 
              type='b', lwd=2,
              ylab='Bias', xlab = 'Sample size',
              panel= function(x, y, ...){
                panel.grid()
                panel.xyplot(x, y, ..., col='black')
                panel.abline(h=0, col='gray', ..., lty=2)
                },
              main = "Bias"
              )
print(test)
```


```{r}
trellis.device(color=FALSE, new=FALSE)

test = xyplot(S.hat.norm + S.hat.t + S.hat.robust ~ n |S_lab, 
              data=out, 
              type='b', lwd=2,
              ylab='Variance', xlab = 'Sample size',
              panel= function(x, y, ...){
                panel.grid()
                panel.xyplot(x, y, ..., col='black')
                panel.abline(h=0, col='gray', ..., lty=2)
                },
              main = "Variance of estimators",
              key = list(columns = 3,
                         text = list(lab = c("normal", "t", "robust")),
                         points = list(pch =c(1, 3, 6)))
              )
print(test)
```


# Fixing x's
```{r}
SimFunc_xfixed <- function(n = 100, alpha = 0.05, m = 1, S = 0.6, x){
  beta = sqrt(S^2) # true beta
  # simulate x and y
  # x = rnorm(n*m) %>% matrix(ncol = m)
  y = x %*% beta + rnorm(n)
  model <- lm(y~ -1 + x)
  beta.hat <- coef(model)
  
  xTx = sum(x^2)
  
  # 1. when sigma is known (sigma = 1)
  # S.hat.norm <- sqrt(beta.hat^2 / (1/sum(x^2)))
  S.hat.norm <- sqrt(beta.hat^2)
  bias.norm <- S.hat.norm - S
  
  # beta.CI = beta.hat + c(-1, 1) * qnorm(1-alpha/2) * sqrt(1/sum(x^2))  
  # Constructing the CI for beta from non-central dist
  z = beta.hat/sqrt(1/sum(x^2)) # normal dist
  chi = z^2 # Chi-sq (1)
  CI_ncp = ncc.ints(yl = sqrt(chi), p = 1, alpha = alpha)[1, ]^2 # this function produces CI for \sqrt(chi^2)
  # CI for beta^2
  # beta2.CI = CI_ncp* (1/sum(x^2))
  # beta.CI = sqrt(beta2.CI)
  # CI for S
  S.CI.norm = sqrt(CI_ncp/n)
  
  # whether the CI for beta covers the true S
  # beta.cvg.norm = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.norm <- c(0, sqrt(max(abs(beta.CI))^2))
  # } else {
  #   S.CI.norm <- c(sqrt(min(abs(beta.CI))^2), sqrt(max(abs(beta.CI))^2))
  # }

  
  # when sigma in unknwon
  # 2. naive estimator for sigma^2
  resd <- residuals(model)
  sigma2_y.hat <- sum(resd^2)/(n-m)
  sigma2_x.hat <- xTx/n
  var.beta.hat = (xTx/n)^(-1) * sigma2_y.hat / n
  
  S.hat.t <- sqrt(beta.hat^2/ (n*var.beta.hat))
  bias.t = S.hat.t - S
  
  t = beta.hat/sqrt(var.beta.hat) # t dist w. df = 1
  f = t^2 # F(1, n-1)
  CI_ncp = ncf.ci(y = f, df1 =1, df2 = n-1, alpha = alpha) 
  S.CI.t = sqrt(CI_ncp/n)
  
  # beta.CI = beta.hat + c(-1, 1) * c( qt(1-alpha/2, df = n-1) * sqrt(var.beta.hat) )
  
  # whether the CI for beta covers the true S
  # beta.cvg.t = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.t <- c(0, sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat ) ) )
  # } else {
  #   S.CI.t<- c(sqrt(min(abs(beta.CI))^2 /(n*var.beta.hat) ), sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat) ))
  # }
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.t <- c(0, sqrt(max(abs(beta.CI))^2  ) )
  # } else {
  #   S.CI.t<- c(sqrt(min(abs(beta.CI))^2  ), sqrt(max(abs(beta.CI))^2  ))
  # }
  
  # 3. using HC3 estimator
  var.beta.hat <- sandwich::vcovHC(model)
  
  beta.CI = beta.hat + c(-1, 1) * c( qt(1-alpha/2, df = n-1)*sqrt(var.beta.hat) )
  
  # whether the CI for beta covers the true S
  # beta.cvg.robust = ifelse(beta.CI[1] <= S & S <= beta.CI[2],
  #                        1, 0)
  
  S.hat.robust <- sqrt(beta.hat^2/ (n*var.beta.hat))
  bias.robust <- S.hat.robust - S
  
  # Constructing CI for S using non-central F and transformation
  t = beta.hat/sqrt(var.beta.hat) # t dist w. df = 1
  f = t^2 # F(1, n-1)
  CI_ncp = ncf.ci(y = f, df1 =1, df2 = n-1, alpha = alpha) 
  S.CI.robust = sqrt(CI_ncp/n)
  
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.robust<- c(0, sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat )) )
  # } else {
  #   S.CI.robust<- c(sqrt(min(abs(beta.CI))^2 /(n*var.beta.hat) ), sqrt(max(abs(beta.CI))^2 /(n*var.beta.hat) ))
  # }
  # if (beta.CI[1]*beta.CI[2] < 0 ){
  #   S.CI.robust<- c(0, sqrt(max(abs(beta.CI))^2 ) )
  # } else {
  #   S.CI.robust<- c(sqrt(min(abs(beta.CI))^2  ), sqrt(max(abs(beta.CI))^2))
  # }
  
  output = c(
            # normal
             S.hat.norm, bias.norm, 
             S.CI.norm,
             coverage.norm = (S >= S.CI.norm[1] & S <= S.CI.norm[2]), 
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.norm.prob = S < S.CI.norm[1],
             UL.norm.prob = S > S.CI.norm[2],
             # beta.cvg.norm, 
             # t-dist
             S.hat.t, bias.t,
             S.CI.t,
             coverage.t = (S >= S.CI.t[1] & S <= S.CI.t[2]),
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.t.prob = S < S.CI.t[1],
             UL.t.prob = S > S.CI.t[2],
             # beta.cvg.t, 
             # robust
             S.hat.robust, bias.robust,
             S.CI.robust,
             coverage.robust = (S >= S.CI.robust[1] & S <= S.CI.robust[2]),
             # the probabilty/proportion of true S failling on the left or right of the CI
             LL.prob.robust = S < S.CI.robust[1],
             UL.prob.robust = S > S.CI.robust[2]
             # beta.cvg.robust
             )
  
  name_list1 = c("S.hat.", "Bias.", "LL.", "UL.", "coverage.", "LL.prob.", "UL.prob.")
  name_list2 = c("norm", "t", "robust")
  names(output) = c(paste0(rep(name_list1, times = length(name_list2)), 
                           rep(name_list2, each = length(name_list1))) )
  return(output)
} # end of SimFunc_xfixed()
```

```{r sim_setting_x_fixed, eval=FALSE}
set.seed(111)
nsim = 1000
alpha = 0.05
ns = c(50, 100, 150, 250, 500)
Ss = seq(0, 0.9, by = 0.1)
m = 1

name_list1 = c("S.hat.", "Bias.", "LL.", "UL.", "coverage.", "LL.prob.", "UL.prob.")
name_list2 = c("norm", "t", "robust")

out = expand.grid(n = ns, S = Ss)
names <- SimFunc_xfixed(n = 10, S = 0.1, x = rnorm(10) %>% matrix(ncol = 1)) %>% names()

for (n in ns){
  for (S in Ss){
    message(paste(n, S), collapse = ",")
    x = rnorm(n*m) %>% matrix(ncol = m) 
    xTx = t(x) %*% x
    x = sqrt(n)*x/c(sqrt(xTx))
    temp = replicate(nsim, SimFunc_xfixed(n = n, S = S, x = x)) %>% t()
    out[which(out$n == n & out$S == S), names] <- c(var(temp[, 1]), colMeans(temp[, 2:7] ) ,
                                                    var(temp[, 8]), colMeans(temp[, 9:14]),
                                                    var(temp[, 15]), colMeans(temp[, 16:21])
                                                    )
  }
}

# write.csv(out, "Simulation outputs/CIs_Simple_Case_x_fixed_May7.csv")
```

## Plots
```{r}
out_xfixed = read.csv("Simulation outputs/CIs_Simple_Case_x_fixed_May7.csv", header = TRUE)
out_xfixed$S_lab = paste("S =", out$S) # convert to label string
```

```{r}
trellis.device(color=FALSE, new=FALSE)

test = xyplot(coverage.norm + coverage.t + coverage.robust ~ n | S_lab , 
              data=out_xfixed, 
              type='b', lwd=2,
              ylab='Coverage', xlab = 'Sample size',
              panel= function(x, y, ...){
                panel.grid()
                panel.xyplot(x, y, ..., col='black')
                panel.abline(h=0.95, col='gray', ..., lty=2)
                }, 
              main='CI coverage',
              key = list(columns = 3,
                         text = list(lab = c("normal", "t", "robust")),
                         points = list(pch =c(1, 3, 6)))
              )
print(test)
```

